### ISSUE TITLE
Bug: Manage e-mail confirmation link does not work except in original browser session

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-ponymail#43]
The manage e-mail process sends out an e-mail with a link.
However the link does not work unless the same browser session is used.

**Comment by sebbASF** [comment]
If the link is used in a session which is not logged in, the server responds with a large JSON dump of email statistics rather than an error message

**Comment by sebbASF** [comment]
If it's not possible to fix the code so the URL works in any browser session, a simple solution would be to only provide the hash in the e-mail confirmation. The hash could then be entered on a ponymail page.
The current process is very awkward and unintuitive.

**Comment by sebbASF** [comment]
The dump of email stats was fixed as part of #305 

The email now makes it clear that you need to be logged in

**Comment by murukeshm** [comment]
This is still happening. I tried to add  an email just now, and got a dump of JSON, which seems to be counts of posts in each domain's lists.

**Comment by sebbASF** [comment]
The code has been fixed, but the updated code has yet to be deployed.
